[package]
name = "mountain_sakura"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
uuid = { version = "1.11.0", features = ["fast-rng", "v4"] }
indexmap = "2.10.0"
jni = "0.21.1"
lazy_static = "1.5.0"

[lib]
crate-type = ["cdylib"]